services:

  postgres:
    image: postgres:16
    container_name: credit-risk-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      GENAI_API_KEY: ${GENAI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: ${BACKEND_URL}
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: